openapi: 3.0.3
info:
  title: Device manager and telemetry service API
  description: API для управления устройствами и телеметрии
  version: 1.0.0

paths:
  /houses:
    post:
      summary: Добавить новый дом
      description: Добавить новый дом в БД
      requestBody:
        description: Информация о доме
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Адрес дома
                description:
                  type: string
                  description: Описание дома
                  example: "Загородный дом"
                user_id:
                  type: string
                  format: uuid
                  description: Уникальный идентификатор пользователя
              required:
                - address
                - owner_id
      responses:
        '201':
          description: Новый дом успешно добавлен
        '400':
          description: Некорректный запрос
        '500':
          description: Ошибка сервера

  /houses/{house_id}:
    get:
      summary: Получить информации о доме
      description: Информацяия о доме по его идендификатору.
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор дома
      responses:
        '200':
          description: Информация о доме возвращена
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор дома
                  address:
                    type: string
                    description: Адрес дома
                  description:
                    type: string
                    description: Описание дома
                  user_id:
                    type: string
                    format: uuid
                    description: uuid пользователя
                  devices:
                    type: array
                    items:
                      type: string
                      format: uuid
                    description: Список uuid устройств зарегистрированных в этом доме
                required:
                  - id
                  - address
                  - owner_id
        '404':
          description: Дом не найден
        '500':
          description: Ошибка сервера

    put:
      summary: Отредактировать информации о доме
      description: Обновление информацию о доме по его uuid.
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор дома
      requestBody:
        description: Данные для обновления информации о доме
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Новый адрес дома
                user_id:
                  type: string
                  format: uuid
                  description: Uuid пользователя
              required:
                - address
                - user_id
      responses:
        '200':
          description: Информация о доме успешно обновлена
        '400':
          description: Некорректный запрос
        '404':
          description: Дом не найден
        '500':
          description: Ошибка сервера

    delete:
      summary: Удалить дом
      description: Удаляет дом по его Uuid
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Uuid дома
        - name: remove_linked_devices
          in: path
          required: true
          schema:
            type: boolean
          description: Необходимость удаления связанных устройства с домом
      responses:
        '204':
          description: Дом успешно удален
        '404':
          description: Дом не найден

  /houses/{house_id}/devices:
    get:
      summary: Получить список uuid устройств в доме
      description: Возвращает список уникальных идентификаторов устройств в доме
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор дома
      responses:
        '200':
          description: Список устройств возвращен
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
                description: Список идентификаторов устройств
        '404':
          description: Дом не найден
        '500':
          description: Ошибка сервера

  /houses/{house_id}/devices/{device_id}:
    put:
      summary: Привязать устройство с домом
      description: Добавляет устройство в дом.
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор дома
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '200':
          description: Устройство успешно привязано
        '404':
          description: Дом или устройство не найдены
        '500':
          description: Ошибка сервера

    delete:
      summary: Удалить устройство из дома
      description: Удаляет устройство из дома.
      parameters:
        - name: house_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор дома
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '200':
          description: Устройство успешно удалено
        '404':
          description: Дом или устройство не найдены
        '500':
          description: Ошибка сервера        

  /devices:
    post:
      summary: Добавить новое устройство
      description: Добавляет новое устройство в БД
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: Уникальный идентификатор пользователя
                name:
                  type: string
                  example: "Лампа"
                description:
                  type: string
                  example: "Лампа в детской"
                type:
                  type: string
                  example: "Освещение"
                serial_number:
                  type: string
              required:
                - user_id
                - name
                - type
                - serial_number
      responses:
        '201':
          description: Устройство успешно добавлено
        '400':
          description: Неверный запрос

  /devices/{device_id}:
    get:
      summary: Получить информацию об устройстве
      description: Возвращает информацию об устройстве по его идентификатору.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '200':
          description: Информация об устройстве
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  user_id:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор пользователя, которому принадлежит устройство
                  name:
                    type: string
                  description:
                    type: string
                  type:
                    type: string
                  serial_number:
                    type: string
                required:
                  - id
                  - user_id
                  - name
                  - description
                  - type
                  - serial_number
        '404':
          description: Устройство не найдено

    delete:
      summary: Удалить устройство
      description: Удаляет устройство по его идентификатору.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '204':
          description: Устройство успешно удалено
        '404':
          description: Устройство не найдено

  /devices/{device_id}/telemetry/latest:
    get:
      summary: Получение последних данных телеметрии
      description: Возвращает последнее значение телеметрии по идентификатору устройства.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
      responses:
        '200':
          description: Данные телеметрии успещно возвращены
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                    description: Дата и время получения данных
                  data:
                    type: object
                    additionalProperties: true
                    description: Данные телеметрии
                required:
                  - timestamp
                  - data
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /devices/{device_id}/telemetry/range:
    get:
      summary: Получение данных телеметрии за выбранный период
      description: Возвращает данные телеметрии по идентификатору устройства за определённый период времени.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
        - name: begin
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Начала периода
        - name: end
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Окончание периода
      responses:
        '200':
          description: Днные возвращены
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                          description: Дата и время получения данных
                        data:
                          type: object
                          additionalProperties: true
                          description: Данные телеметрии
                      required:
                        - timestamp
                        - data
                required:
                  - data
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера